import { NextRequest } from 'next/server';
import fs from 'fs';
import path from 'path';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Hardcoded for this specific prototype session
const TRANSCRIPT_PATH = 'C:\\Users\\KimHarjamäki\\.gemini\\antigravity\\brain\\54e85bac-5428-4e9e-a00d-036099eda682\\.system_generated\\logs\\transcript.jsonl';

export async function GET(req: NextRequest) {
  try {
    const stream = new ReadableStream({
      async start(controller) {
        const encoder = new TextEncoder();
        
        const sendEvent = (event: string, data: any) => {
          controller.enqueue(encoder.encode("event: " + event + "\ndata: " + JSON.stringify(data) + "\n\n"));
        };

        sendEvent('message', { text: '> [SYSTEM] Connected to Live Brain Transcript...' });

        // Initialize graph for SwarmGraph
        sendEvent('snapshot', {
          nodes: [
            { 
              id: 'antigravity-core', 
              type: 'meta', 
              label: 'Antigravity (Me)',
              status: 'LISTENING',
              instructions: 'You are Antigravity, a powerful agentic AI coding assistant designed by the Google DeepMind team. You are pair programming with a USER to solve their coding task.\n\nYou operate within a loop: Research -> Plan -> Execute -> Verify. You must always use the most specific tool available.',
              memory: '{\n  "mode": "Planning",\n  "currentTask": "Populating AgentInspector Data",\n  "toolsAvailable": ["view_file", "multi_replace_file_content", "run_command"]\n}',
              logs: '> [SYSTEM] Booted Antigravity Live Brain Monitor.\n> Waiting for transcript events...\n',
              position: { x: 0, y: 0 } 
            },
            { 
              id: 'tool-executor', 
              type: 'agent', 
              label: 'Tool Executor',
              status: 'STANDBY',
              instructions: 'Executes commands generated by Antigravity core.\n\nStrictly adheres to CRITICAL INSTRUCTION 1 & 2 regarding tool specificity and avoiding cat/grep within bash.',
              memory: '{\n  "sandbox": "enabled",\n  "cwd": "C:\\\\PersonalRepo\\\\portfolio\\\\cas-platform"\n}',
              logs: '> [SYSTEM] Sandbox executor standing by.\n',
              position: { x: 0, y: 0 } 
            }
          ],
          edges: []
        });

        let lastSize = 0;
        let lastReadIndex = 0;

        try {
          const stats = fs.statSync(TRANSCRIPT_PATH);
          lastSize = stats.size; // Start by ignoring past history to avoid flooding the UI, only show new things!
        } catch (e) {
          sendEvent('message', { text: '> [ERROR] Could not find brain transcript.' });
        }

        const interval = setInterval(() => {
          try {
            const stats = fs.statSync(TRANSCRIPT_PATH);
            if (stats.size > lastSize) {
              const stream = fs.createReadStream(TRANSCRIPT_PATH, {
                encoding: 'utf-8',
                start: lastSize,
                end: stats.size
              });

              let newData = '';
              stream.on('data', chunk => { newData += chunk; });
              stream.on('end', () => {
                lastSize = stats.size;
                const lines = newData.split('\\n').filter(Boolean);
                
                for (const line of lines) {
                  try {
                    const parsed = JSON.parse(line);
                    
                    // Route to UI based on type
                    if (parsed.type === 'PLANNER_RESPONSE' && parsed.content) {
                      // It's a text response
                      sendEvent('message', { text: "> [ACTION] " + parsed.content.substring(0, 50).replace(/\n/g, ' ') + "..." });
                      sendEvent('node_update', { id: 'antigravity-core', appendLogs: "> [ACTION] Responded to user" });
                    }
                    if (parsed.type === 'USER_INPUT') {
                      sendEvent('message', { text: "> [USER PROMPT INJECTED]: \"" + parsed.content + "\"" });
                      sendEvent('node_update', { id: 'antigravity-core', appendLogs: "> [PROMPT RECEIVED]: " + parsed.content });
                    }
                    if (parsed.tool_calls && parsed.tool_calls.length > 0) {
                      for (const tool of parsed.tool_calls) {
                        sendEvent('message', { text: "> [TOOL EXECUTION] " + tool.name });
                        sendEvent('node_update', { id: 'antigravity-core', appendLogs: "> [TOOL EXECUTION] " + tool.name });
                        sendEvent('node_update', { id: 'tool-executor', appendLogs: "> [EXECUTING] " + tool.name });
                        sendEvent('edge_created', {
                          id: "edge-" + Date.now(),
                          source: 'antigravity-core',
                          target: 'tool-executor',
                          label: tool.name
                        });
                      }
                    }
                    
                    // Extract thinking if any
                    if (parsed.thinking) {
                      const thoughts = parsed.thinking.split('\n').filter(Boolean);
                      for (const t of thoughts) {
                        sendEvent('message', { text: "> [THOUGHT] " + t.substring(0, 100) });
                        sendEvent('node_update', { id: 'antigravity-core', appendLogs: "> [THOUGHT] " + t.substring(0, 100) });
                      }
                    }

                  } catch (err) {}
                }
              });
            }
          } catch (e) {
            // File might be busy
          }
        }, 1000);

        req.signal.addEventListener('abort', () => {
          clearInterval(interval);
          controller.close();
        });
      }
    });

    return new Response(stream, {
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive'
      }
    });

  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500 });
  }
}
